service: tc-lambda-dice-health
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - ${file(./config/${self:provider.stage}.json):VPC_SECURITY_GROUP_ID_1}
      - ${file(./config/${self:provider.stage}.json):VPC_SECURITY_GROUP_ID_2}
    subnetIds:
      - ${file(./config/${self:provider.stage}.json):VPC_SUBNET_ID_1}
  role: ${file(./config/${self:provider.stage}.json):LAMBDA_ROLE}
  runtime: nodejs12.x
  memorySize: 256
  timeout: 15
  environment:
    REDIS_URL: ${file(./config/${self:provider.stage}.json):REDIS_URL}
    DICE_URL: ${file(./config/${self:provider.stage}.json):DICE_URL}

functions:
  handler:
    handler: lambda.handler
    name: ${self:provider.stage}-tc-lambda-dice-health # optional, Deployed Lambda name
    description: DICE health checker # The description of your function.
    events:
      - http: ANY /
